name 'conjur_ui'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures conjur_ui'
long_description 'Installs/Configures conjur_ui'
version '0.1.0'
